---
- name: Create schedule
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  vars:
    start_year: "2024"
    start_month: "08"
    start_day: "21"
    start_hour: "14"
    start_minute: "00"
    cluster_name: "SAP"

  collections:
  - awx.awx

  tasks:
  - name: One time schedule for patching the cluster
    awx.awx.schedule:
      name: "patch_cluster_{{ cluster_name }}"
      unified_job_template: "[WF] Patch cluster {{ cluster_name }}"
      state: present
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      rrule: "DTSTART;TZID=Europe/Brussels:{{ start_year }}{{ start_month }}{{ start_day }}T{{ start_hour }}{{ start_minute }}00 RRULE:FREQ=MINUTELY;INTERVAL=1;COUNT=1"
    register: schedule_result
