---
- name: Create my schedule
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  vars:
    start_year: "2024"
    start_month: "08"
    start_day: "21"
    start_hour: "14"
    start_minute: "00"
    cluster_name: "SAP"

  collections:
  - ansible.controller

  tasks:
  - name: Deleting schedule
    awx.awx.schedule:
      name: "patch_cluster_{{ cluster_name }}"
      state: absent
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
    register: schedule_result