---
- name: Create my schedule
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  vars:
    start_year: "2024"
    start_month: "08"
    start_day: "21"
    start_hour: "14"
    start_minute: "00"
    cluster_name: 

  collections:
  - ansible.controller

  tasks:
  - name: One time schedule for patching the cluster
    awx.awx.schedule:
      name: "{{ customer }} patch cluster"
      unified_job_template: "[WF] Patch cluster SAP"
      state: absent
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      rrule: "DTSTART:{{ start_year }}{{ start_month }}{{ start_day }}T{{ start_hour }}{{ start_minute }}51Z RRULE:FREQ=NONE;INTERVAL=1;COUNT=1"
    register: schedule_result